### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dheimgartner** [dheimgartner/surveytools#2]
# Master
- [ ] Specify surveyJS dependencies in `.yaml` -> see `htmltools` https://cran.r-project.org/web/packages/htmltools/htmltools.pdf
    - how to download the js library? (see surveyJS documentation...)
    - see sigma example: https://github.com/jjallaire/sigma/tree/master/inst/htmlwidgets/lib/sigma-1.0.3 -> with node `npm`... right?
- [ ] How to implement communication from JS to R?
    - via javascript binding... or
    - via `htmlwidgets::onRender` (and access the returned js object from the binding...
    - see `dygraphs` for using widget data: https://github.com/rstudio/dygraphs/
 - [ ] Communication from R to JS (among others) via JS callback functions: https://www.htmlwidgets.org/develop_advanced.html (see SurveyJS doc for stuff to send).
    - I think these would be passed as argument in the `survey.R` function `survey <- function(js_callback)` and then passed to `survey.js` via `x`. See here: https://github.com/rstudio/dygraphs/blob/master/R/callbacks.R
 - [ ] It would be nice to have individual element bindings / tools which then could be piped together: Simple example:
    - again see `dygraphs` example: https://github.com/rstudio/dygraphs/
    - https://book.javascript-for-r.com/widgets-adv.html

```{R}
## output$radio_button <-
radioButton() %>%
add_question("What's your favourite food?") %>%
add_label("favourite_food") %>%
add_options(c("pizza" = "Pizza", "thai" = "Thai Curry", "sushi" = "Sushi") %>% 
assign_to_input(). ## or some other way...
```

- [x] How to handle resizing? (see vignette as a starting point and check if surveyJS has a resize method...
- [ ] `survey_creator` widget should directly allow to save json somehow
- [ ] `survey_json` will be serialized when passed to survey.js. Instead of passing it as `json` we could pass it as `data.frame` (of some form) or `list` and then take care of the correct serialization.
    - See custom JSON seralizer: https://www.htmlwidgets.org/develop_advanced.html

**Comment by dheimgartner** [comment]
# 12.02.2022
- [ ] Take care of searialization (optimally via data.frame or list)
- [x] How to communicate from JS to R?
- [ ] ~~Create very simple survey_json on SurveyJS for one question type~~
- [ ] ~~Write own widget for that question type~~
- [x] Implement pipe style (should be possible to both render the widget by passing fully defined widget or in chronological steps with pipes

**Comment by dheimgartner** [comment]
# 18.02.2022
- [x] Merge page and survey widget -> everything will be implemented in survey widget
- [x] Implement core question stuff: https://surveyjs.io/Documentation/Library?id=Question
- [x] Implement most important question types: text, dropdown, radiogroup, ...
- [x] `onValueChanged()` not required to specify name (unless called with `survey_json`)
- [x] Send answers to Shiny (both for `survey_json` and pipe-strategy -> in particular if `showNavigationButtons("off")` -> `doComplete()`
- [x] Test multipage pipe (if multiple new pages are added and questions injected on particular pages)
- [ ] Could we pass shiny modules to SurveyJS `html` question -> maybe passed as html to list...?
- [ ] Cache answers in browser (see screenshot)

**Comment by dheimgartner** [comment]
# JavaScript "Backend"
- If one could use the SurveyJS backend for storing answers, one could very easily do "simple" (only implemented in SurveyJS) surveys (e.g. via HTML [implemented in RMarkdown])...

**Comment by dheimgartner** [comment]
# 27.02.2022

- How to crossreference questions from different survey instances?
- I've seen on surveyjs that you can create multiple instances and simply reference questions by name (however, in htmlwidget survey objects are not in same scope...?

```{R}
library(shiny)

devtools::load_all()


survey1 <-
  survey() %>%
  showNavigationButtons("none") %>%
  addNewPage("s1p1") %>%
  addNewQuestion("text") %>%
  title("What's your name?") %>%
  name("name") %>%
  inputType("text") %>%
  addNewQuestion("text") %>%
  title("How old are you?") %>%
  name("age") %>% 
  inputType("number") %>%
  requiredIf("{name} == Daniel") %>%
  onRender(jsCode = "
           function(el, x) {
              window.survey1 = this;
           }
           ")

survey2 <-
  survey() %>%
  showNavigationButtons("none") %>% 
  addNewPage("s2p1") %>%
  addNewQuestion("text") %>%
  title("How old are you?") %>%
  name("age") %>% 
  inputType("number") %>%
  requiredIf("{name} == Daniel") %>%
  onRender(jsCode = "
           function(el, x) {
              window.survey2 = this;
           }
           ")

# TODO: implement custom registered function
# requiredIf("fromSurvey('survey1', {name}) == Daniel) or something like that

ui <- fluidPage(
  surveyOutput("survey1"),
  HTML("<p>Shiny action</p>"),
  surveyOutput("survey2")
)

server <- function(input, output, session) {
  output$survey1 <- renderSurvey(survey1)
  output$survey2 <- renderSurvey(survey2)
}

shinyApp(ui, server)
```
